theme = "catppuccin_mocha"

[editor]
line-number = "relative"
bufferline = "multiple"
color-modes = true
rulers = [100]
auto-save = true
true-color = true

[editor.indent-guides]
render = true
character = "┆"
skip-levels = 1

[editor.lsp]
display-messages = true

[keys.normal]
Y = ":yank-join"
X = "extend_line_above"
D = "delete_char_backward"
F3 = [":fmt", ":wa"]
F4 = ":pipe sort"
A-u = "switch_to_uppercase"
A-l = "switch_to_lowercase"
F12 = ":config-open"
A-F12 = ":open ~/.config/helix/languages.toml"

[editor.statusline]
mode.normal = "󰫻"
mode.insert = "󱂈"
mode.select = "󱎤"
