theme = "catppuccin_mocha"

[editor]
line-number = "relative"
bufferline = "multiple"
color-modes = true
rulers = [100]
auto-save = true
true-color = true

[editor.indent-guides]
render = true
character = "┆"
skip-levels = 1

[editor.lsp]
display-messages = true

[keys.normal]
X = "extend_line_above"
D = "delete_char_backward"
F3 = [":fmt", ":wa"]
F4 = ":pipe sort"

[editor.statusline]
mode.normal = "󰫻"
mode.insert = "󱂈"
mode.select = "󱎤"
