[language-server.typos]
command = "typos-lsp"

[language-server.sql-language-server]
command = "sql-language-server"
args = ["up", "--method", "stdio"]

[language-server.ltex-ls.config]
ltex.enabled = true
ltex.completionEnabled = true
ltex.statusBarItem = true
ltex.language = "ru-RU"
ltex.dictionary = { "ru-RU" = ["builtin"] }

[language-server.helix-snippets-ls]
command = "helix-snippets-ls"
args = ["--stdio"]

[language-server.gpt]
command = "helix-gpt"
args = [
  "--logFile",        "/tmp/gpt-helix-gpt.log",
  "--handler",        "ollama",
  "--ollamaModel",    "llama3.2:1b",
  "--ollamaEndpoint", "http://172.20.7.20:11434",
]

##### Language: MARKDOWN #####
[[language]]
name = "markdown"
language-servers = [ "ltex-ls" ]

##### Language: DOCKERFILE #####
[[language]]
name = "dockerfile"
language-servers = [ "docker-langserver", "typos" ]
indent = { tab-width = 4, unit = "    " }

##### Language: PHP #####
[[language]]
name = "php"
auto-format = true
language-servers = [ "intelephense", "typos", "helix-snippets-ls", "gpt" ]

[language.auto-pairs]
"'" = "'"
'<' = '>'
'(' = ')'
'{' = '}'
'[' = ']'
'`' = '`'
'"' = '"'

[language.debugger]
name = "php"
transport = "stdio"
command = "node"
args = ["~/gits/vscode-php-debug/out/phpDebug.js"]

[[language.debugger.templates]]
name = "source"
request = "launch"
completion = [ { name = "entrypoint", completion = "filename"} ]
args = { mode = "debug", program = "{0}" }

##### Language: SQL #####
[[language]]
name = "sql"
language-servers = [ "sql-language-server", "typos" ]

##### Language: BASH #####
[[language]]
name = "bash"
language-servers = [ "bash-language-server", "typos" ]

##### Language: JAVASCRIPT #####
[[language]]
name = "javascript"
language-servers = [ "typescript-language-server", "typos" ]
indent = { tab-width = 4, unit = "    " }

##### Language: CSS #####
[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "typos" ]
indent = { tab-width = 4, unit = "    " }

##### Language: GIT-COMMIT #####
[[language]]
name = "git-commit"
language-servers = [ "typos", "ltex-ls" ]

##### Language: PYTHON #####
[[language]]
name = "python"
formatter = { command = "black", args = ["-q", "-"] }
auto-format = true
