#
##
### LSP settings
##
#

### typos
[language-server.typos]
command = "typos-lsp"

### sql-language-server
[language-server.sql-language-server]
command = "sql-language-server"
args = ["up", "--method", "stdio"]

### ltex-ls
[language-server.ltex-ls.config]
ltex.enabled = true
ltex.completionEnabled = true
ltex.statusBarItem = true
ltex.language = "ru-RU"
ltex.dictionary = { "ru-RU" = ["builtin"] }

### helix-snippets
[language-server.helix-snippets-ls]
command = "helix-snippets-ls"
args = ["--stdio"]

### helix-gpt
[language-server.gpt]
command = "helix-gpt"
args = [
  "--logFile",        "/tmp/gpt-helix-gpt.log",
  "--handler",        "openai",
  "--openaiModel",    "deepseek-chat",
  "--openaiEndpoint", "https://api.deepseek.com/v1",
]

#
##
### Languages settings
##
#

### MARKDOWN
[[language]]
name = "markdown"
language-servers = [ "ltex-ls" ]

### DOCKERFILE
[[language]]
name = "dockerfile"
language-servers = [ "docker-langserver", "typos" ]
indent = { tab-width = 4, unit = "    " }

### PHP
[[language]]
name = "php"
auto-format = true
# language-servers = [ "intelephense", "typos", "helix-snippets-ls", "lsp-ai" ]
# language-servers = [ "lsp-ai" ]
language-servers = [ "gpt" ]

[language.auto-pairs]
"'" = "'"
'<' = '>'
'(' = ')'
'{' = '}'
'[' = ']'
'`' = '`'
'"' = '"'

[language.debugger]
name = "php"
transport = "stdio"
command = "node"
args = ["~/gits/vscode-php-debug/out/phpDebug.js"]

[[language.debugger.templates]]
name = "source"
request = "launch"
completion = [ { name = "entrypoint", completion = "filename"} ]
args = { mode = "debug", program = "{0}" }

### SQL
[[language]]
name = "sql"
language-servers = [ "sql-language-server", "typos" ]

### BASH
[[language]]
name = "bash"
language-servers = [ "bash-language-server", "typos" ]

### JAVASCRIPT
[[language]]
name = "javascript"
language-servers = [ "typescript-language-server", "typos" ]
indent = { tab-width = 4, unit = "    " }

### CSS
[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "typos" ]
indent = { tab-width = 4, unit = "    " }

### GIT
[[language]]
name = "git-commit"
language-servers = [ "typos", "ltex-ls" ]

### PYTHON
[[language]]
name = "python"
formatter = { command = "black", args = ["-q", "-"] }
auto-format = true
